[package]
name = "simple-auth-server"
edition = "2024"
rust-version = "1.85"

[dependencies]
actix-identity = "0.9"
actix-session = { version = "0.11", features = ["cookie-session"] }
actix-web = "4.11"
actix-files = "0.6"
actix-cors = { version = "0.7" }

chrono = { version = "0.4.30", features = ["serde"] }
derive_more = { version = "2", features = ["display"] }
diesel = { version = "2", features = ["postgres", "r2d2", "uuid", "chrono"] }
dotenvy = "0.15"
futures-util = "0.3"
env_logger = "0.11"
jsonwebtoken = "9.2"
log = "0.4"
lazy_static = "*"
once_cell = "1"
openidconnect = { git = "https://github.com/devflowinc/openidconnect-rs.git", rev = "9b9cefd91ae7e1bc4ad336a9bed5dcf04fa179a5", features = [
    "reqwest",
    "accept-rfc3339-timestamps",
], default-features = false }
oauth2 = "4.4.2"
r2d2 = "0.8"
rust-argon2 = "2"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
sparklepost = "0.5"
temp-env = "0.3"
time = "0.3"
uuid = { version = "1.6", features = ["v4", "v7", "serde"] }
ssmtp = "1.0.1"
